name: cmake

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
    - name: Init Submodules
      run: git submodule update --init

    - name: Build
      shell: bash
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .
